### ISSUE TITLE
2.0.0a4 is ~2.5 times slower than 0.8.4

### ISSUE THREAD

**Issue by a-vrma** [lepture/mistune#235]
Was benchmarking and noticed that mistune 2.0.0a4 is around 2.5 times slower than 0.8.4 on the benchmark suite over at https://github.com/miyuchina/mistletoe. The results I got were surprising:

```
mistune 0.8.4: 8.952760785999999
mistune 2.0.0a4: 23.15826605300026
```

Interestingly, this puts mistune's speed at a comparable level to mistletoe, which has a far more robust and spec-compliant parser. Is this something that you are looking to fix with the final 2.0 release?

**Comment by lepture** [comment]
I'm not sure if it can be faster in mistune v2. I'll still work on it. But v0.8.4 is not robust, there are cases which will make 0.8.4 very slow.

As for spec-compliant? I think you mean Commonmark. Commonmark cares too much about weird cases instead of normal cases. 

For instance, In Commonmark:

```
[<https://lepture.com>](/hello)
```

Will be rendered as:

```
<p><a href="/hello"><a href="https://lepture.com">https://lepture.com</a></a></p>
```

This is certainly wrong. And they defined many rules for weird cases that I personally don't like. Just like John Gruber said in https://twitter.com/gruber/status/507615356295200770:

> Only two maybes I’ve thought of: Strict Markdown or Pedantic Markdown. “Strict” still doesn’t seem right.

If you like a "strict" common mark, mistune is not your choice.

**Comment by lepture** [comment]
Not an issue report, close it.
