### ISSUE TITLE
Strange behavior of newlines

### ISSUE THREAD

**Issue by boxed** [lepture/mistune#248]
```
>>> import mistune
>>> markdown = mistune.create_markdown()
>>> markdown('foo\n  bar')
'<p>foo\n  bar</p>\n'
>>> markdown('foo \n  bar')
'<p>foo \n  bar</p>\n'
>>> markdown('foo  \n  bar')
'<p>foo<br />\n  bar</p>\n'
```

I believe this is incorrect. The output should have a <br> between those two lines always, it shouldn't depend on two spaces before newline.

**Comment by boxed** [comment]
I'm using version 2.0.0a4 btw.

**Comment by karlcow** [comment]
This is correct.
[line break](https://daringfireball.net/projects/markdown/syntax#p)

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.

**Comment by boxed** [comment]
Oh. Ugh. https://stackedit.io/ doesn't follow that, nor https://dillinger.io/, or https://markdown-editor.github.io/, and not github either:

foo
bar

baz

Maybe a plugin/option for this might make sense I guess. Depends on usage. I want to use mistune for a forum/wiki, and then it is very confusing and bad doing what the markdown spec says. Just pasting some python code into a comment field would mangle it badly.

**Comment by karlcow** [comment]
@boxed I guess it depends on your usage. Because for me this is the opposite. I'm using this feature on my own system. The [GFM (GitHub Flavored Markdown)](https://github.github.com/gfm/) behavior seems also to mandate that.

* For stackedit, [this is configurable](https://github.com/benweet/stackedit/issues/1142#issuecomment-476791123).
* for dillinger I [filed an issue](https://github.com/joemccann/dillinger/issues/764)
*  for markdown-editor, the[ issue was closed](https://github.com/terrylinooo/githuber-md/issues/155), because it was saying it was behaving the right way.

**Comment by lepture** [comment]
This can be done with a custom InlineParser right now. But I think it would be good to make an option for it.

**Comment by lepture** [comment]
I've added `hard_wrap` back into the master code.
