### ISSUE TITLE
Mistune 3: regression parsing links with parenthesis

### ISSUE THREAD

**Issue by davidbgk** [lepture/mistune#355]
Markdown source: `[The Menu](https://en.wikipedia.org/wiki/The_Menu_(2022_film)) (essayez de ne pas vous divulgâcher…).`

Previously with Mistune 2 the HTML was:

```html
<a href="https://en.wikipedia.org/wiki/The_Menu_(2022_film)">The Menu</a> (essayez de ne pas vous&nbsp;divulgâcher…).
```

With Mistune 3 it becomes:

```html
<a href="https://en.wikipedia.org/wiki/The_Menu_(2022_film">The Menu</a>) (essayez de ne pas vous&nbsp;divulgâcher…).
```

I see why it can be an issue but I'm not sure where to look for the dedicated regexp. At least, this is a basic testcase :)

**Comment by davidbgk** [comment]
Maybe it's the `LINK_HREF_INLINE_RE` pattern or `PAREN_END_RE` has to be used somehow 🤔

**Comment by lepture** [comment]
It requires some time to make it correct, for now you can wrap the url with `<>`:

```
[The Menu](<https://en.wikipedia.org/wiki/The_Menu_(2022_film)>) (essayez de ne pas vous divulgâcher…).
```

**Comment by davidbgk** [comment]
I wasn't aware of that syntax, thanks for the trick it solved the parenthesis issue 🙇

**Comment by andrei-akopian** [comment]
I think I found the regex: `URL_LINK_PATTERN=https?:\/\/[^\s<]+[^<.,:;"')\]\s]` in [url.py line 12](https://github.com/lepture/mistune/blob/93fd197c6c24353011974110378b738596cde5a1/src/mistune/plugins/url.py#L12)

Here is regex101 for it: https://regex101.com/r/pNcJhM/5

The current regex does the following: match the `https://` protocol, then any number of characters (including parentheses brackets) that is not a whitespace (`[^\s<]+`), but make sure that the match ends before the closing parenthesis of the hyperlink. (`[^<.,:;"')\]\s]`)
(Links like `https://example.com/Alan_(Mathison)_Turing` will match correctly despite having parentheses, because it ends with a normal character)

Now how do we fix this? I fear that some other edgecase might depend on the way this specific regex behavior...

Here is a [StackOverflow thread on matching urls](https://stackoverflow.com/questions/6038061/regular-expression-to-find-urls-within-a-string) but they are all huge (like `(?:(?:https?|ftp|file):\/\/|www\.|ftp\.)(?:\([-A-Z0-9+&@#\/%=~_|$?!:,.]*\)|[-A-Z0-9+&@#\/%=~_|$?!:,.])*(?:\([-A-Z0-9+&@#\/%=~_|$?!:,.]*\)|[A-Z0-9+&@#\/%=~_|$])`)

I wrote my own smaller solution based on the old regex: `https?:\/\/([^\s<()]+|\([^\s<()]+\))+`

I am bad at Regex, so I would prefer a more experienced dev to test and add it.

And to give you more headache: what happens if there are nested parentheses?

**Comment by lepture** [comment]
This is actually a bad design by Markdown. Since URL can contain `(` and `)`, the syntax should not use `()` to wrap the link.

Original Markdown: Dingus: https://daringfireball.net/projects/markdown/dingus
commonmark.js dingus: https://spec.commonmark.org/dingus/

Test cases:

```
[The Menu](https://en.wikipedia.org/wiki/The_Menu_(2022_film))(foo)

// Markdown Dingus:
<p><a href="https://en.wikipedia.org/wiki/The_Menu_(2022_film">The Menu</a>)(foo)</p>

// CommonMark:
<p><a href="https://en.wikipedia.org/wiki/The_Menu_(2022_film)">The Menu</a>(foo)</p>
```

CommonMark is correct for this case. But what if the URL contains non-paired `()`?

Some URLs:

```
https://example.com/parenthesis-of-)
https://example.com/parenthesis-of-(
https://example.com/parenthesis-of-))
```

So I suggest using `<>` to wrap the url. The `<>` syntax is also supported by CommonMark.
