### ISSUE TITLE
Certain characters in inline code incorrectly parsed (e.g., `&`)

### ISSUE THREAD

**Issue by nschloe** [lepture/mistune#372]
MWE:

```python
import mistune
from mistune.core import BlockState
markdown = mistune.create_markdown(renderer="ast")

md = r"`&<>`"
tokens = markdown(md)

print(tokens)
```

Output:

```python
[{'type': 'paragraph', 'children': [{'type': 'codespan', 'raw': '&amp;&lt;&gt;'}]}]
```

**Comment by torokati44** [comment]
We also encountered this. The cause is 8452faf345a152a149e7f79243fd9693a06ed0e9.
Putting HTML escaping into the _parser_ stage, independent of the output, is incorrect.

**Comment by veenstrajelmer** [comment]
I also encountered this, originally found in https://github.com/omnilib/sphinx-mdinclude/issues/19. I did some digging and found that the issue lays in `mistune.util.escape_url` indeed as @torokati44 points towards, but only because its behavior is different depending on whether `html` is installed (this happens in the import):
https://github.com/lepture/mistune/blob/93fd197c6c24353011974110378b738596cde5a1/src/mistune/util.py#L32-L39

Some code to reproduce:
```python
from urllib.parse import quote
import html

link = "https://sonarcloud.io/api/project_badges/measure?project=Deltares_ddlpy&metric=alert_status"

# code from: def escape_url(link):
safe = (
    ':/?#@'           # gen-delims - '[]' (rfc3986)
    '!$&()*+,;='      # sub-delims - "'" (rfc3986)
    '%'               # leave already-encoded octets alone
)
out_nonhtml = quote(link.encode('utf-8'), safe=safe)
out_withhtml = html.escape(quote(html.unescape(link), safe=safe))
out_withhtml_noescape = quote(html.unescape(link), safe=safe)

print(out_nonhtml)
print(out_withhtml)
print(out_withhtml_noescape)
```

This gives different results. The first one is returned if `html` is not installed, the second one if `html` is installed. The third one is correct again:
```
https://sonarcloud.io/api/project_badges/measure?project=Deltares_ddlpy&metric=alert_status
https://sonarcloud.io/api/project_badges/measure?project=Deltares_ddlpy&amp;metric=alert_status
https://sonarcloud.io/api/project_badges/measure?project=Deltares_ddlpy&metric=alert_status
```

Therefore, what I think should fix the issue is to remove the `html.escape()` from the function

**Comment by itcarroll** [comment]
I'm going down the rabbit hole from jupyter-book > sphinx > myst > ??? here, maybe? I'm getting `&amp;` in markdown links that include query parameters. Any workaround?

**Comment by veenstrajelmer** [comment]
I think what you are encountering is because of the bug described in this issue indeed. No workaround as far as I know, @lepture could you ahare your thoughts on this discussion?

**Comment by mentalisttraceur** [comment]
@itcarroll actually, Jupyter's MyST uses [`markdown-it-py`](https://pypi.org/project/markdown-it-py), not Mistune.

**Comment by mentalisttraceur** [comment]
@veenstrajelmer I think you've spotted a *separate* issue. Similar, but independent code paths. The inline *code* escaping just uses `escape`, not `escape_url`.

**Comment by veenstrajelmer** [comment]
@mentalisttraceur ok fair, but will this issue be resolved? I see limited response from maintainers of this repository, so I am not sure what to expect. If it is a different issue, does it help if I create a different issue, or will it not matter too much? I am a bit hesitant in putting even more investigation time in this package, because of te limited response. My issue is just a single readme badge that does not work in the docs of all my packages (e.g. https://deltares.github.io/dfm_tools). I can relatively easily convert all the readme's from markdown to rst, but only raised this issue since I prefer markdown.

**Comment by stdedos** [comment]
@veenstrajelmer "not having this discussion here", would matter _at least_ for us that are "actively" participating on this issue 🤷
You can also clearly see that someone decided to step up and fix this issue (after this issue being stale for a while).

I would be optimistic - as long as issues don't get "more tangled".

**Comment by veenstrajelmer** [comment]
I was not intending to tangle issues, just noticed this issue that seems pretty much as what I am running into. I do not see how they are caused and therefore also not see how they are unrelated. To me they both come down to incorrect character escaping in mistune, but apparently they have different causes. Either way, I have created another issue here: https://github.com/lepture/mistune/issues/394.
